version: '3.9'

services:

  fastapi:
    build: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env

  web:
    build: ./frontend
    ports:
      - "8000:8000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - ./frontend/.env
    depends_on:
      - fastapi
